/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 46;
  /** RegularExpression Id. */
  int ID = 47;
  /** RegularExpression Id. */
  int LETTER = 48;
  /** RegularExpression Id. */
  int DIGIT = 49;
  /** RegularExpression Id. */
  int UNDER = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"extends\"",
    "\"Thread\"",
    "\"synchronized\"",
    "\"return\"",
    "\"boolean\"",
    "\"int\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"Xinu\"",
    "\"new\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"null\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUM>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "\"=\"",
    "\"!\"",
  };

}
